version: '2'
services:
  db:
    image: mysql:5.6.23
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes_from:
      - datastore

  nginx:
    build: containers/nginx
    ports:
      - '8080:80'
    volumes_from:
      - datastore
    links:
      - web

  datastore:
    build: containers/datastore

  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      RAILS_ENV: development
      MYSQL_ROOT_PASSWORD: password
    volumes_from:
      - datastore
    depends_on:
      - db