# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd5e5968a96c88572b0333aac1824807a77e89299615bf386ed179c12123f3e0f447b5b8af4b3e46b9fe165b2747aa4f37cde7ca7cf88486a5fbbae27facf2b1

test:
  secret_key_base: 92d7d573ca74cb90d830c4015b08524d14dd516100d64100f8174e834033d1191d3bc2c3b318ef93c492445057c5771c8f578d5ea71c4c714c8cc6f6a7f00e39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
